### ISSUE TITLE
NullPointerException in 1.9.1

### ISSUE THREAD

**Issue by jegr78** [jenkinsci/envinject-plugin#41]
Jenkins 1.602
Stacktrace:
```
    Failed to record SCM polling for hudson.maven.MavenModuleSet@15f65b19[PROJECT]
    java.lang.NullPointerException
    at org.jenkinsci.plugins.envinject.EnvInjectPluginAction$1.transformEntry(EnvInjectPluginAction.java:25)
    at org.jenkinsci.plugins.envinject.EnvInjectPluginAction$1.transformEntry(EnvInjectPluginAction.java:23)
    at com.google.common.collect.Maps$TransformedEntriesMap$1$1.apply(Maps.java:1218)
    at com.google.common.collect.Maps$TransformedEntriesMap$1$1.apply(Maps.java:1216)
    at com.google.common.collect.Iterators$8.next(Iterators.java:812)
    at java.util.AbstractMap.putAll(AbstractMap.java:280)
    at java.util.TreeMap.putAll(TreeMap.java:327)
    at org.jenkinsci.plugins.envinject.EnvInjectVarList.<init>(EnvInjectVarList.java:26)
    at org.jenkinsci.plugins.envinject.EnvInjectPluginAction.getTarget(EnvInjectPluginAction.java:22)
    at org.jenkinsci.plugins.envinject.EnvInjectPluginAction.buildEnvVars(EnvInjectPluginAction.java:31)
    at hudson.model.AbstractBuild.getEnvironment(AbstractBuild.java:929)
    at hudson.maven.AbstractMavenBuild.getEnvironment(AbstractMavenBuild.java:56)
    at hudson.maven.MavenModuleSetBuild.getEnvironment(MavenModuleSetBuild.java:167)
    at hudson.plugins.git.GitSCM.compareRemoteRevisionWithImpl(GitSCM.java:564)
    at hudson.plugins.git.GitSCM.compareRemoteRevisionWith(GitSCM.java:526)
    at hudson.scm.SCM.compareRemoteRevisionWith(SCM.java:380)
    at hudson.scm.SCM.poll(SCM.java:397)
    at hudson.model.AbstractProject._poll(AbstractProject.java:1446)
    at hudson.model.AbstractProject.poll(AbstractProject.java:1349)
    at jenkins.triggers.SCMTriggerItem$SCMTriggerItems$Bridge.poll(SCMTriggerItem.java:119)
    at hudson.triggers.SCMTrigger$Runner.runPolling(SCMTrigger.java:515)
    at hudson.triggers.SCMTrigger$Runner.run(SCMTrigger.java:544)
    at hudson.util.SequentialExecutionQueue$QueueEntry.run(SequentialExecutionQueue.java:118)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by oleg-nenashev** [comment]
Please submit the issue to Jenkins JIRA

**Comment by jegr78** [comment]
Issue in Jenkins JIRA: https://issues.jenkins-ci.org/browse/JENKINS-27342
